### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CodeWithKaushal** [jahongir7174/SimpleNet#5]
(env) (base) aapl17@aapl17:~/Framebased_Annomaly_testing/SimpleNet_new$ python main.py --train

     epoch    memory      true      fake      loss
     1/150        3G    0.1273    0.1705     1.403: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:09<00:00,  1.47it/s]
                  f1       acc   roc_auc       auc: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:02<00:00,  4.28it/s]
Traceback (most recent call last):
  File "/home/aapl17/Framebased_Annomaly_testing/SimpleNet_new/main.py", line 223, in <module>
    main()
  File "/home/aapl17/Framebased_Annomaly_testing/SimpleNet_new/main.py", line 217, in main
    train(args)
  File "/home/aapl17/Framebased_Annomaly_testing/SimpleNet_new/main.py", line 102, in train
    last = test(args, device, save_g, save_d)
  File "/home/aapl17/Framebased_Annomaly_testing/env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/aapl17/Framebased_Annomaly_testing/SimpleNet_new/main.py", line 198, in test
    roc_auc, auc, f1, accuracy = util.compute_metrics(scores, labels)
  File "/home/aapl17/Framebased_Annomaly_testing/SimpleNet_new/utils/util.py", line 55, in compute_metrics
    roc_auc = metrics.roc_auc_score(targets, outputs)
  File "/home/aapl17/Framebased_Annomaly_testing/env/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/aapl17/Framebased_Annomaly_testing/env/lib/python3.9/site-packages/sklearn/metrics/_ranking.py", line 630, in roc_auc_score
    raise ValueError("multi_class must be in ('ovo', 'ovr')")
ValueError: multi_class must be in ('ovo', 'ovr')

**Comment by CodeWithKaushal** [comment]
.
